# Datensatz Desiderius Erasmus Stiftung
Codebuch Stand 07.03.2022


## EDGE-Attribute

**id** 
eindeutige Codierung des Knoten für jeweils einen Akteur (Person oder Organisation)

**status**
1 = aktiv
2 = Inaktiv

**relation** 
Art der Beziehung
1 = mit Verantwortung
2 = Mitglied, involviert
3 = Unterstützung
4 = Erwähnung

**entry** 
Erster öffentlicher Kontakt
JJJJ-MM

**exit**
Letzter öffentlicher Kontakt
JJJJ-MM

## NODE-Attribute
**id** 
durchlaufende Nummer

**type** 
handelt es sich um einen Person oder eine Organisation?
1 = Organisation
2 = Person

**kind** 
1 = Person
2 = Partei
3 = Vertriebenenverband
4 = Burschenschaft
5 = Medium
6 = Sonstiges
7 = DES

**name** 
voller Name, ausgeschrieben, ohne Titel

**name_short**
abgekürzter Name

**sex** 
Geschlecht der Personen
1 = weiblich
2 = männlich
3 = Organisation
4 = divers

**age** 
Alter der Personen
1 = bis 40
2 = 41 bis 50 Jahre
3 = 51 bis 60 Jahre
4 = 60 und älter
5 = Tod

**bundesland** 
1 = Baden-Württemberg
2 = Bayern
3 = Berlin
4 = Brandenburg
5 = Bremen
6 = Hamburg
7 = Hessen
8 = Mecklenburg-Vorpommern
9 = Niedersachsen
10 = Nordrhein-Westfalen
11 = Rheinland-Pfalz
12 = Saarland
13 = Sachsen
14 = Sachsen-Anhalt
15 = Schleswig-Holstein
16 = Thüringen
17 = Deutschland
18 = Interntional
19 = Österreich

**education** 
Bildungsstand
1 = Abitur
2 = Bachelor
3 = Master
4 = Doktor
5 = Professor 
6 = Sonstiges
7 = Kein höherer Bildungsabschluss

**subject**  
Fachrichtung der Bildung
1 = Wirtschaft
2 = Jura
3 = Geisteswissenschaften
4 = Naturwissenschaften
5 = Technik
6 = Handwerk
7 = Sonstiges

**afd** 
atkuell Mitgliedschaft von Personen in der Partei Alternative für Deutschland
1 = Ja
2 = Nein
3 = Ehemalig

**law_conflict** 
stand die Person/Organisation im Konfilt mit dem Gesetz
1 = Nein
2 = Verklagt wegen rechter Einstellung
3 = Beobachtung durch den Verfassungsschutz
